---
  VMs_root: "/home/vmPool"
  VMs_base_images: "{{VMs_root}}/baseVMs"
  VMs_images: "{{VMs_root}}/CoeGSS"
  VMS_image_prefix: "CoeGSS"
  VMS_image_owner: "qemu"
  VMS_image_group: "qemu"
  VMs_data_image_size: "100G"
  VMs_dhcp_pool: "172.18.2.0/23" # IP pool from DHCP
