---
- name: ensure custom facts directory exists
  file:
    path: "/etc/ansible/facts.d"
    recurse: yes
    state: directory

- name: install custom fact module for IP address
  template:
    src: "{{item}}.fact.j2"
    dest: "/etc/ansible/facts.d/{{item}}.fact"
    mode: 0755
  with_items:
    - apache_version
    - openssl_version

- name: reload ansible_local
  setup: filter=ansible_local