---
#Postgres vars
postgresql_pgtune: false
postgresql_encoding: 'UTF-8'
postgresql_locale_parts:
  - 'en_US' # Locale
  - 'UTF-8' # Encoding
postgresql_locale: "{{ postgresql_locale_parts | join('.') }}"
postgresql_admin_user: "postgres"

dbname: coegss_qa
dbuser: coegss
dbpassword: 'CoeGSS_QA'  

#askbot variables
askbotuser: askbot
home_dir: /home/{{askbotuser}}
django_project: coegss_askbot
django_dir: '{{ home_dir }}/{{ django_project }}'


#server variables
vm_ip: '172.18.10.54'
server_name: 'askbot.coegss.hlrs.de'
vm_name: 'packer-ubuntu-16'


