---
ansible_become: True
#ckan_venv_path: "/usr/lib/ckan/default"
ckan_version: "2.8.0"
ckan_pip_url: "git+https://github.com/ckan/ckan.git@ckan-{{ckan_version}}#egg=ckan"
ckan_db_user: "ckan_default"
ckan_db_pass: "ckan_dHLRSb_pass"
ckan_db_name: "ckan_default"
ckan_sys_user: "ckan"
ckan_setup_tools_version: "36.1"

ckan_venv_path: "/home/{{ckan_sys_user}}/venv"

#Postgres vars
postgresql_pgtune: false
postgresql_encoding: 'UTF-8'
postgresql_locale_parts:
  - 'en_US' # Locale
  - 'UTF-8' # Encoding
postgresql_locale: "{{ postgresql_locale_parts | join('.') }}"
postgresql_admin_user: "postgres"

#server variables
vm_ip: '172.18.10.54'
server_name: 'ckan.coegss.hlrs.de'
vm_name: 'packer-ubuntu-16'