---
www_root: "/var/www/ckan"
www_host: "test-vm"
www_proto: "http"
webserver_user: "www-data"
webserver_group: "www-data"

# php_fpm_pool_user: "{{webserver_user}}"
# php_fpm_pool_group: "{{webserver_group}}"
nginx_user: "{{webserver_user}}"
nginx_group: "{{webserver_group}}"
nginx_official_repo: True

nginx_http_params:
  - sendfile on
  - access_log /var/log/nginx/access.log
  - error_log /var/log/nginx/error.log
nginx_sites:
  ckan:
     - listen 80
     - server_name "{{www_host}}"
     - server_tokens off
     - location ^~ /.well-known/acme-challenge/ {  root "{{www_root}}"; }
     - location / { return 301 https://$server_name$request_uri; }
  ckan_ssl:
     - listen 443 ssl default deferred http2
     - server_name "{{www_host}}"
     - server_tokens off
     - ssl on
     - ssl_certificate         /etc/letsencrypt/live/{{ www_host }}/fullchain.pem
     - ssl_certificate_key     /etc/letsencrypt/live/{{ www_host }}/privkey.pem
     - ssl_trusted_certificate /etc/letsencrypt/live/{{ www_host }}/fullchain.pem

     - ssl_session_cache shared:SSL:50m
     - ssl_session_timeout 1d
     - ssl_stapling on
     - ssl_stapling_verify on

     - ssl_protocols TLSv1.2
     - ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256'

     - ssl_dhparam /etc/nginx/dhparams.pem
     - ssl_prefer_server_ciphers on

     - add_header Strict-Transport-Security max-age=15768000

     - root "{{www_root}}"

     # - location / { index index.php; }
     # -  |
     #    location ~ ^/admin/.*?[^/]\.php(/|$) {
     #        fastcgi_split_path_info  ^(.+\.php)(/.+)$;
     #        fastcgi_index            index.php;
     #        fastcgi_pass             "{{php_fpm_listen}}";
     #        include                  fastcgi_params;
     #        fastcgi_param   PATH_INFO       $fastcgi_path_info;
     #        fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
     #        fastcgi_read_timeout 600;
     #    }
     # -  |
     #    location ~ [^/]\.php(/|$) {
     #        fastcgi_split_path_info  ^(.+\.php)(/.+)$;
     #        fastcgi_index            index.php;
     #        fastcgi_pass             "{{php_fpm_listen}}";
     #        include                  fastcgi_params;
     #        fastcgi_param   PATH_INFO       $fastcgi_path_info;
     #        fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
     #    }

 